package Interfaz;

import AlgoritmosOrdenamiento.MergeSort;
import AlgoritmosOrdenamiento.QuickSort;
import AlgoritmosOrdenamiento.ShellSort;
import Estructuras.AvlTreeTest;
import Estructuras.ListaEnlazadaTest;

/**
 * Clase encarga de mostrar las duraciones de los distintos ordenamientos
 *
 * @author Juan Miguel Arias Mejias
 * @author Ana Teresa Quesada Ramírez
 */
public class VentanaMediciones extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMediciones
     */
    public VentanaMediciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tiemposArea = new javax.swing.JTextArea();
        inicioB = new javax.swing.JButton();
        salirB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mediciones de tiempo y ordenamiento");

        tiemposArea.setEditable(false);
        tiemposArea.setColumns(20);
        tiemposArea.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        tiemposArea.setRows(5);
        tiemposArea.setToolTipText("Aquí se muestran los tiempos de ejecución. MM:SS:mm");
        jScrollPane1.setViewportView(tiemposArea);

        inicioB.setText("Iniciar Test");
        inicioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioBActionPerformed(evt);
            }
        });

        salirB.setText("Salir");
        salirB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(inicioB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salirB)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inicioB)
                    .addComponent(salirB))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioBActionPerformed
        // TODO add your handling code here:

        String tree = new AvlTreeTest().getFormatTime();
        String insertion = new ListaEnlazadaTest().getFormatTime();
        String mergeSort = new MergeSort().getFormatTime();
        String quickSort = new QuickSort().getFormatTime();
        String shellSort = new ShellSort().getFormatTime();
        // RADIX SORT HERE!

        StringBuilder sb = new StringBuilder();
        sb.append("\n\n---- Tiempos de ejecución ----\n\n");
        sb.append("--- Árbol AVL ---\n");
        sb.append(tree).append("\n");
        sb.append("--- Ordenamiento por Insercion ---\n");
        sb.append(insertion).append("\n");
        sb.append("\n\n--- Algoritmos de ordenamiento ---\n\n");
        sb.append("-- MergeSort --\n");
        sb.append(mergeSort).append("\n");
        sb.append("-- QuickSort --\n");
        sb.append(quickSort).append("\n");
        sb.append("-- ShellSort --\n");
        sb.append(shellSort).append("\n");

        this.tiemposArea.setText(sb.toString());
    }//GEN-LAST:event_inicioBActionPerformed

    private void salirBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMediciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMediciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMediciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMediciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMediciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inicioB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salirB;
    private javax.swing.JTextArea tiemposArea;
    // End of variables declaration//GEN-END:variables
}
